### PR TITLE
update singularity to 3.6.2

### PR DESCRIPTION
**Pull request by AcaDemIQ**

### CODE REVIEW

**Comment by czka** [comment]
@AcaDemIQ
Thanks!

It won't build on my box:

```
makepkg -s -L -f
(...)
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
 GEN /home/dane/devel/aur/singularity-container/src/singularity/src/github.com/sylabs/singularity/scripts/go-generate
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
package github.com/sylabs/singularity/cmd/singularity
	imports github.com/sylabs/singularity/cmd/internal/cli
	imports github.com/sylabs/singularity/internal/app/singularity
	imports github.com/sylabs/singularity/internal/pkg/build
	imports github.com/sylabs/singularity/internal/pkg/build/sources
	imports github.com/sylabs/singularity/internal/pkg/client/library
	imports github.com/sylabs/singularity/internal/app/singularity: import cycle not allowed
make: *** [Makefile:172: singularity] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

Please try reproducing this. If it builds for you, maybe the problem is related to my setup. If so, I can look into it again next week.

**Comment by AcaDemIQ** [comment]
@czka I have built singularity package again :)
There is my full log from `makepkg` program:
```
❯ makepkg -s -L -f
==> Making package: singularity-container 3.6.2-3 (Thu 10 Sep 2020 05:26:23 PM +07)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading singularity-3.6.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152  100   152    0     0    371      0 --:--:-- --:--:-- --:--:--   370
100   648  100   648    0     0    923      0 --:--:-- --:--:-- --:--:--   923
100 5794k  100 5794k    0     0   340k      0  0:00:17  0:00:17 --:--:--  504k
==> Validating source files with md5sums...
    singularity-3.6.2.tar.gz ... Passed
==> Extracting sources...
==> Starting prepare()...
==> Starting build()...
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.13)... /usr/bin/go
 checking: host C compiler option -Wall... yes
 checking: host C compiler option -Werror... yes
 checking: host C compiler option -Wfatal-errors... yes
 checking: host C compiler option -Wno-unknown-warning-option... yes
 checking: host C compiler option -Wstrict-prototypes... yes
 checking: host C compiler option -Wpointer-arith... yes
 checking: host C compiler option -Wbad-function-cast... yes
 checking: host C compiler option -Woverlength-strings... yes
 checking: host C compiler option -Wframe-larger-than=2047... yes
 checking: host C compiler option -Wno-sign-compare... yes
 checking: host C compiler option -Wclobbered... yes
 checking: host C compiler option -Wempty-body... yes
 checking: host C compiler option -Wmissing-parameter-type... yes
 checking: host C compiler option -Wtype-limits... yes
 checking: host C compiler option -Wunused-parameter... yes
 checking: host C compiler option -Wunused-but-set-parameter... yes
 checking: host C compiler option -Wno-discarded-qualifiers... yes
 checking: host C compiler option -Wno-incompatible-pointer-types... yes
 checking: host C compiler option -pipe... yes
 checking: host C compiler option -fmessage-length=0... yes
 checking: host C compiler option -fPIC... yes
 checking: host `ar' path... ar
 checking: host `ld' path... ld
 checking: host `ranlib' path... ranlib
 checking: host `objcopy' path... objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... ar
 checking: target `ld' path... ld
 checking: target `ranlib' path... ranlib
 checking: target `objcopy' path... objcopy
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: project version... 3.6.2
 checking: project short version... 3.6.2
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... yes
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: libseccomp+headers... yes
 checking: cryptsetup... yes
=> generating fragments ...
=> building Makefile ...
=> generating singularity.spec ...
=> project singularity setup with :
    - host arch: x86_64
    - host wordsize: 64-bit
    - host C compiler: cc
    - host Go compiler: /usr/bin/go
    - host system: unix
      ---
    - target arch: x86_64
    - target wordsize: 64-bit
    - target C compiler: cc
      ---
    - config profile: release
      ---
    - SUID install: yes
    - Network plugins: yes
      ---
    - verbose: no
      ---
    - cryptsetup: /usr/bin/cryptsetup
      ---
    - version: 3.6.2
=> /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/builddir/Makefile ready, try:
   $ cd /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/builddir
   $ make
 GEN GO DEP /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/builddir/starter.d
go: downloading github.com/seccomp/libseccomp-golang v0.9.1
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/seccomp/containers-golang v0.6.0
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/sylabs/sif v1.2.1
go: downloading github.com/sylabs/golang-x-crypto v0.0.0-20181006204705-4bce89e8e9a9
go: downloading github.com/opencontainers/runtime-spec v1.0.3-0.20200710190001-3e4195d92445
go: downloading github.com/kr/pty v1.1.8
go: downloading github.com/containerd/cgroups v0.0.0-20200116170754-a8908713319d
go: downloading github.com/sylabs/json-resp v0.7.0
go: downloading golang.org/x/sys v0.0.0-20200720211630-cb9d2d5c5666
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/creack/pty v1.1.9
go: downloading github.com/sylabs/scs-key-client v0.5.1
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading github.com/containernetworking/plugins v0.8.6
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading mvdan.cc/sh/v3 v3.1.2
go: downloading github.com/containernetworking/cni v0.8.0
go: downloading github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: downloading github.com/opencontainers/selinux v1.6.0
go: downloading github.com/coreos/go-iptables v0.4.5
go: downloading github.com/godbus/dbus v4.1.0+incompatible
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading golang.org/x/term v0.0.0-20191110171634-ad39bd3f0407
go: downloading github.com/vishvananda/netlink v1.0.1-0.20190618143317-99a56c251ae6
go: downloading github.com/coreos/go-systemd/v22 v22.0.0-20191111152658-2d78030078ef
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading github.com/safchain/ethtool v0.0.0-20190326074333-42ed695e3de8
go: downloading github.com/willf/bitset v1.1.11-0.20200630133818-d5bec3311243
go: downloading github.com/godbus/dbus/v5 v5.0.3
go: downloading github.com/vishvananda/netns v0.0.0-20180720170159-13995c7128cc
 GEN GO DEP /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/builddir/singularity.d
go: downloading github.com/go-log/log v0.2.0
go: downloading github.com/containers/image/v5 v5.5.2
go: downloading github.com/spf13/cobra v1.0.0
go: downloading github.com/vbauerster/mpb/v4 v4.12.2
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/sylabs/scs-build-client v0.1.4
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: downloading github.com/opencontainers/image-spec v1.0.2-0.20191218002246-9ea04d1f37d7
go: downloading github.com/opencontainers/umoci v0.4.6-0.20200622135030-30d116059d97
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/containerd/containerd v1.4.0
go: downloading github.com/deislabs/oras v0.8.1
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/vbauerster/mpb/v5 v5.2.2
go: downloading github.com/containers/storage v1.20.2
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/containers/ocicrypt v1.0.2
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/docker/docker-credential-helpers v0.6.3
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: downloading github.com/spf13/pflag v1.0.5
go: downloading go.etcd.io/bbolt v1.3.4
go: downloading github.com/klauspost/compress v1.10.9
go: downloading github.com/klauspost/pgzip v1.2.4
go: downloading github.com/sylabs/scs-library-client v0.5.5
go: downloading google.golang.org/protobuf v1.24.0
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/apex/log v1.9.0
go: downloading github.com/containers/libtrust v0.0.0-20190913040956-14b96171aa3b
go: downloading github.com/opencontainers/runc v1.0.0-rc90
go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/urfave/cli v1.22.4
go: downloading github.com/pquerna/ffjson v0.0.0-20190813045741-dac163c6c0a9
go: downloading github.com/rootless-containers/proto v0.1.0
go: downloading github.com/vbatts/go-mtree v0.5.0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/ulikunitz/xz v0.5.7
go: downloading github.com/gorilla/mux v1.7.4
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/docker/go-metrics v0.0.1
go: downloading github.com/fullsailor/pkcs7 v0.0.0-20190404230743-d7302db945fa
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading google.golang.org/grpc v1.27.0
go: downloading github.com/prometheus/client_golang v1.1.0
go: downloading github.com/cyphar/filepath-securejoin v0.2.2
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/prometheus/common v0.6.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/prometheus/procfs v0.0.5
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
 GEN /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/scripts/go-generate
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
 GEN etc/bash_completion.d/singularity
 GEN singularity.conf from /etc/singularity/singularity.conf
 CNI PLUGIN dhcp
 CNI PLUGIN host-local
 CNI PLUGIN static
 CNI PLUGIN bridge
 CNI PLUGIN host-device
 CNI PLUGIN ipvlan
 CNI PLUGIN loopback
 CNI PLUGIN macvlan
 CNI PLUGIN ptp
 CNI PLUGIN vlan
 CNI PLUGIN bandwidth
 CNI PLUGIN firewall
 CNI PLUGIN flannel
 CNI PLUGIN portmap
 CNI PLUGIN tuning
 GO clean -cache
 GO cmd/starter/c/starter
 GO cmd/starter/c/starter-suid
    [+] GO_TAGS "containers_image_openpgp sylog singularity_engine fakeroot_engine apparmor selinux seccomp"
 GEN /home/alex/new_singularity/AUR-singularity-container/src/singularity/src/github.com/sylabs/singularity/scripts/go-test
==> Entering fakeroot environment...
==> Starting package()...
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/bin/singularity
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/bash_completion.d/singularity
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/singularity.conf
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/remote.yaml
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/dhcp
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/host-local
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/static
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/bridge
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/host-device
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/ipvlan
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/loopback
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/macvlan
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/ptp
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/vlan
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/bandwidth
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/firewall
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/flannel
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/portmap
 INSTALL CNI PLUGIN /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/cni/tuning
 INSTALL CNI CONFIGURATION FILES
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/bin/starter
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/var/singularity/mnt/session
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/bin/run-singularity
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/capability.json
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/ecl.toml
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/seccomp-profiles/default.json
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/nvliblist.conf
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/rocmliblist.conf
 INSTALL /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/etc/singularity/cgroups/cgroups.toml
 INSTALL SUID /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/libexec/singularity/bin/starter-suid
 DONE
mkdir -p /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/share/man/man1
INFO:    Creating Singularity man pages at /home/alex/new_singularity/AUR-singularity-container/pkg/singularity-container/usr/share/man/man1
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> WARNING: Package contains reference to $srcdir
usr/bin/singularity
usr/libexec/singularity/bin/starter
usr/libexec/singularity/bin/starter-suid
==> Creating package "singularity-container"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: singularity-container 3.6.2-3 (Thu 10 Sep 2020 05:30:00 PM +07)
```

**Comment by AcaDemIQ** [comment]
Maybe need to restore .SRCINFO file?

**Comment by alhirzel** [comment]
@AcaDemIQ it built for me, I made the new PR with `.SRCINFO`

**Comment by czka** [comment]
@AcaDemIQ @alhirzel 
The missing `.SRCINFO` file is not an issue, although it's better when you guys include it in an MR. Use `makepkg --printsrcinfo > .SRCINFO` for that, after updating `PKGBUILD`.

I must have had some mess in my `src/` dir in the `makepkg`'s working dir. After `rm -rf src/ pkg/` build passed.

**Pull request merged**
