### PR TITLE
Remove dep from dependencies

### PR DESCRIPTION
**Pull request by micwoj92**
Pozdrawiam ;)

### CODE REVIEW

**Comment by czka** [comment]
@micwoj92 Cheers and pozdro :).

Just to make sure: Are you 100% positive this simplification doesn't break any of the changes intended by their authors in the follwing PRs?
1. https://github.com/czka/AUR-singularity-container/pull/2/files
2. https://github.com/czka/AUR-singularity-container/pull/3/files
3. https://github.com/czka/AUR-singularity-container/pull/9/files

@ilmagico and @apeltzer (regarding #2), @SebastianM-C (regarding #3), @BotoX (regarding #9) - could you gentlemen please doublecheck on your side whether we aren't going to over-simplify or break stuff by any chance with this PR?

**Comment by micwoj92** [comment]
I didn't touch anything related to #9, that line is the same.  It shouldn't affect anything. Only proof I have is 2 packages made with old and new PKGBUILD and they are the same. Same size, same files inside them.

**Comment by ilmagico** [comment]
I haven't used singularity in a long while, I just use plain `docker` or `podman` if I want to run without root. That said ... this change seems to change the `src/github.com/sylabs` directory structure that go requires, or so I thought. Does it still generate a valid package? I'm not super familiar with go, but if the package before and after are exactly the same, it seems ok.

@micwoj92 Same size, same files inside them, and also same content of all files inside? :) If so, I guess it's good.

**Comment by micwoj92** [comment]
> That said ... this change seems to change the `src/github.com/sylabs` directory structure that go requires, or so I thought. 

export GOPATH is no longer required because of the go modules. I think it was changes made in go 1.11 and 1.13

**Comment by SebastianM-C** [comment]
Looks good to me. Thanks for maintaining this.

**Comment by czka** [comment]
Superseded by #15. Thanks @micwoj92 and @hubutui.

**Pull request closed without merging**
